name: Pre-release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'
      - '*.json'
      - '**/wcokey.txt'

concurrency:
  group: "pre-release"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode keystore
      run: |
        KEYSTORE_DIR="${HOME}/work/_temp/keystore"
        mkdir -p "${KEYSTORE_DIR}"
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > "${KEYSTORE_DIR}/velcuri.keystore"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build release APK
      run: ./gradlew assemblePrereleaseRelease
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

    - name: Create pre-release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "pre-release"
        prerelease: true
        title: "Velcuri TV Pre-release"
        files: |
          app/build/outputs/apk/prerelease/release/*.apk
